// 60 realistic incidents across Thailand for heatmap/dashboards
// Mix of types, severity, sources. Spread over last 30 days.

import type { Incident, IncidentType, IncidentSeverity, IncidentSource } from "./types";

function hoursAgo(n: number): string {
  const d = new Date();
  d.setHours(d.getHours() - n);
  return d.toISOString();
}

function rid(prefix: string, n: number): string {
  return `inc-${prefix}-${String(n).padStart(3, "0")}`;
}

interface Spec {
  type: IncidentType;
  severity: IncidentSeverity;
  description: string;
  lat: number;
  lng: number;
  address: string;
  province: string;
  district: string;
  hoursAgo: number;
  reportLagMin: number;
  source: IncidentSource;
  unitId: string;
  status: Incident["status"];
  arrests?: number;
}

const SPECS: Spec[] = [
  // ── Bangkok hotspot cluster (12 incidents) ────────────────────────
  {
    type: "ลักทรัพย์",
    severity: "MEDIUM",
    description: "ลักทรัพย์ในร้านสะดวกซื้อ ถนนสีลม ผู้ต้องหา ๒ คน หลบหนีไปทางรถมอเตอร์ไซค์",
    lat: 13.7244, lng: 100.5343,
    address: "ถ.สีลม ใกล้แยกสีลม", province: "กรุงเทพมหานคร", district: "บางรัก",
    hoursAgo: 6, reportLagMin: 8, source: "ประชาชนแจ้ง",
    unitId: "u-sn-2-2", status: "INVESTIGATING",
  },
  {
    type: "ทำร้ายร่างกาย",
    severity: "HIGH",
    description: "วัยรุ่นยกพวกตีกัน บริเวณหน้าผับย่านทองหล่อ มีผู้บาดเจ็บ ๔ ราย",
    lat: 13.7305, lng: 100.5779,
    address: "ซ.ทองหล่อ ๑๑", province: "กรุงเทพมหานคร", district: "วัฒนา",
    hoursAgo: 12, reportLagMin: 3, source: "191",
    unitId: "u-sn-5-1", status: "CLOSED", arrests: 6,
  },
  {
    type: "ก่อความวุ่นวาย",
    severity: "MEDIUM",
    description: "ม็อบเรียกร้องค่าจ้างที่อนุสาวรีย์ประชาธิปไตย มีประชาชนกว่า ๒๐๐ คน",
    lat: 13.7563, lng: 100.5018,
    address: "อนุสาวรีย์ประชาธิปไตย", province: "กรุงเทพมหานคร", district: "พระนคร",
    hoursAgo: 18, reportLagMin: 2, source: "ตำรวจตรวจพบ",
    unitId: "u-sn-1-1", status: "CLOSED",
  },
  {
    type: "อาชญากรรมออนไลน์",
    severity: "HIGH",
    description: "แก๊งคอลเซ็นเตอร์หลอกผู้สูงอายุ โอนเงิน ๒.๔ ล้านบาท เขตห้วยขวาง",
    lat: 13.7706, lng: 100.5715,
    address: "ถ.รัชดาภิเษก", province: "กรุงเทพมหานคร", district: "ห้วยขวาง",
    hoursAgo: 30, reportLagMin: 720, source: "ประชาชนแจ้ง",
    unitId: "u-sn-4-1", status: "INVESTIGATING",
  },
  {
    type: "อุบัติเหตุ",
    severity: "HIGH",
    description: "รถยนต์ชนกันบนทางด่วนศรีรัช ใกล้ทางลงสาทร มีผู้บาดเจ็บสาหัส ๒ ราย",
    lat: 13.7233, lng: 100.5453,
    address: "ทางด่วนศรีรัช", province: "กรุงเทพมหานคร", district: "สาทร",
    hoursAgo: 4, reportLagMin: 3, source: "191",
    unitId: "u-sn-2-2", status: "CLOSED",
  },
  {
    type: "ยาเสพติด",
    severity: "MEDIUM",
    description: "จับกุมผู้จำหน่ายยาบ้าในชุมชน เขตคลองเตย ของกลางยาบ้า ๓๐๐ เม็ด",
    lat: 13.7058, lng: 100.5870,
    address: "ชุมชนคลองเตย", province: "กรุงเทพมหานคร", district: "คลองเตย",
    hoursAgo: 48, reportLagMin: 0, source: "ข่าวกรอง",
    unitId: "u-sn-5-2", status: "CLOSED", arrests: 1,
  },
  {
    type: "ลักทรัพย์",
    severity: "LOW",
    description: "ขโมยจักรยานยนต์ หน้าหอพักย่านลาดพร้าว",
    lat: 13.7861, lng: 100.5740,
    address: "ลาดพร้าว ซอย ๔๒", province: "กรุงเทพมหานคร", district: "จตุจักร",
    hoursAgo: 72, reportLagMin: 360, source: "ประชาชนแจ้ง",
    unitId: "u-sn-3-3", status: "OPEN",
  },
  {
    type: "ฉ้อโกง",
    severity: "MEDIUM",
    description: "นายหน้าโอนเงินดาวน์รถยนต์ แล้วหายตัวไป ผู้เสียหาย ๘ ราย",
    lat: 13.7461, lng: 100.5345,
    address: "ถ.พระราม ๔", province: "กรุงเทพมหานคร", district: "ปทุมวัน",
    hoursAgo: 96, reportLagMin: 4320, source: "ประชาชนแจ้ง",
    unitId: "u-sn-2-1", status: "INVESTIGATING",
  },
  {
    type: "อาชญากรรมออนไลน์",
    severity: "CRITICAL",
    description: "แฮกเกอร์เจาะระบบธนาคารพาณิชย์ ขโมยข้อมูลลูกค้า ๑๒,๐๐๐ ราย",
    lat: 13.7398, lng: 100.5530,
    address: "อาคารธนาคาร ถ.สุรวงศ์", province: "กรุงเทพมหานคร", district: "บางรัก",
    hoursAgo: 120, reportLagMin: 60, source: "ตำรวจตรวจพบ",
    unitId: "u-bch-special-2", status: "INVESTIGATING",
  },
  {
    type: "ทำร้ายร่างกาย",
    severity: "MEDIUM",
    description: "พ่อใช้กำลังทำร้ายลูกที่บ้าน ผู้บาดเจ็บเป็นเด็กชาย ๘ ขวบ",
    lat: 13.7882, lng: 100.5670,
    address: "ชุมชนพระโขนง", province: "กรุงเทพมหานคร", district: "พระโขนง",
    hoursAgo: 60, reportLagMin: 180, source: "ประชาชนแจ้ง",
    unitId: "u-sn-5-2", status: "CLOSED", arrests: 1,
  },
  {
    type: "อุบัติเหตุ",
    severity: "MEDIUM",
    description: "รถจักรยานยนต์ชนคนข้ามถนน บริเวณแยกราชเทวี",
    lat: 13.7563, lng: 100.5341,
    address: "แยกราชเทวี", province: "กรุงเทพมหานคร", district: "ราชเทวี",
    hoursAgo: 144, reportLagMin: 5, source: "191",
    unitId: "u-sn-4-4", status: "CLOSED",
  },
  {
    type: "ก่อความวุ่นวาย",
    severity: "LOW",
    description: "ทะเลาะวิวาทในร้านอาหาร เขตห้วยขวาง ไม่มีผู้บาดเจ็บสาหัส",
    lat: 13.7800, lng: 100.5740,
    address: "ถ.รัชดาภิเษก ใกล้สี่แยกห้วยขวาง", province: "กรุงเทพมหานคร", district: "ห้วยขวาง",
    hoursAgo: 240, reportLagMin: 4, source: "191",
    unitId: "u-sn-4-1", status: "CLOSED",
  },

  // ── Chiang Mai / ภ.๕ (8 incidents) ────────────────────────────
  {
    type: "ยาเสพติด",
    severity: "HIGH",
    description: "บุกจับโรงงานผลิตยาบ้าในป่า อ.แม่อาย เชียงใหม่ ของกลาง ๔๐ ล้านเม็ด",
    lat: 19.9450, lng: 99.2080,
    address: "อ.แม่อาย", province: "เชียงใหม่", district: "แม่อาย",
    hoursAgo: 96, reportLagMin: 0, source: "ข่าวกรอง",
    unitId: "u-prov-5-ชม", status: "CLOSED", arrests: 8,
  },
  {
    type: "ยาเสพติด",
    severity: "CRITICAL",
    description: "สกัดขบวนการลำเลียงยาบ้าข้ามชายแดน ของกลาง ๑.๒ ล้านเม็ด",
    lat: 19.7305, lng: 99.0044,
    address: "ด่านชายแดนแม่อาย", province: "เชียงใหม่", district: "แม่อาย",
    hoursAgo: 168, reportLagMin: 0, source: "ข่าวกรอง",
    unitId: "u-prov-5-ชม", status: "CLOSED", arrests: 5,
  },
  {
    type: "ลักทรัพย์",
    severity: "LOW",
    description: "ขโมยลักทรัพย์ในวัด ของหายไป ๒ ชิ้น มูลค่าประมาณ ๕,๐๐๐ บาท",
    lat: 18.7883, lng: 98.9853,
    address: "วัดเขตเมือง เชียงใหม่", province: "เชียงใหม่", district: "เมือง",
    hoursAgo: 192, reportLagMin: 60, source: "ประชาชนแจ้ง",
    unitId: "u-prov-5-ชม-st-1", status: "OPEN",
  },
  {
    type: "อุบัติเหตุ",
    severity: "HIGH",
    description: "อุบัติเหตุทางถนน รถบัสนักท่องเที่ยวพลิกคว่ำ บาดเจ็บ ๒๓ ราย",
    lat: 18.9300, lng: 98.9395,
    address: "ทล.๑๐๐๑ ใกล้แม่ริม", province: "เชียงใหม่", district: "แม่ริม",
    hoursAgo: 216, reportLagMin: 2, source: "191",
    unitId: "u-prov-5-ชม", status: "CLOSED",
  },
  {
    type: "ทำร้ายร่างกาย",
    severity: "MEDIUM",
    description: "ทะเลาะวิวาทในงานสงกรานต์ ผู้บาดเจ็บ ๓ ราย",
    lat: 18.7929, lng: 98.9985,
    address: "ถ.ท่าแพ", province: "เชียงใหม่", district: "เมือง",
    hoursAgo: 168, reportLagMin: 5, source: "191",
    unitId: "u-prov-5-ชม-st-1", status: "CLOSED", arrests: 2,
  },
  {
    type: "ฉ้อโกง",
    severity: "MEDIUM",
    description: "หลอกขายของออนไลน์ ผู้เสียหายโอนเงิน ๔๒ ราย ความเสียหายรวม ๑.๒ ลบ.",
    lat: 18.8500, lng: 99.0500,
    address: "อ.สันทราย", province: "เชียงใหม่", district: "สันทราย",
    hoursAgo: 480, reportLagMin: 2880, source: "ประชาชนแจ้ง",
    unitId: "u-prov-5-ชม", status: "INVESTIGATING",
  },
  {
    type: "อาชญากรรมออนไลน์",
    severity: "HIGH",
    description: "แก๊งหลอกลงทุน Cryptocurrency ความเสียหาย ๘.๖ ลบ.",
    lat: 19.9105, lng: 99.8406,
    address: "เชียงราย เมือง", province: "เชียงราย", district: "เมือง",
    hoursAgo: 360, reportLagMin: 720, source: "ประชาชนแจ้ง",
    unitId: "u-bch-5", status: "INVESTIGATING",
  },
  {
    type: "อุบัติเหตุ",
    severity: "CRITICAL",
    description: "รถบรรทุก ๖ ล้อชนรถยนต์นั่ง เสียชีวิต ๓ ราย บาดเจ็บ ๒ ราย",
    lat: 17.6230, lng: 100.0942,
    address: "ทล. ๑๑ จ.ลำปาง", province: "ลำปาง", district: "เมือง",
    hoursAgo: 24, reportLagMin: 3, source: "191",
    unitId: "u-bch-5", status: "CLOSED",
  },

  // ── Phuket / ภ.๘ (6 incidents) ─────────────────────────────────
  {
    type: "ลักทรัพย์",
    severity: "MEDIUM",
    description: "ลักทรัพย์นักท่องเที่ยวต่างชาติ บริเวณหาดป่าตอง",
    lat: 7.8965, lng: 98.2960,
    address: "หาดป่าตอง", province: "ภูเก็ต", district: "กะทู้",
    hoursAgo: 48, reportLagMin: 60, source: "ประชาชนแจ้ง",
    unitId: "u-prov-8-ภก", status: "OPEN",
  },
  {
    type: "ฉ้อโกง",
    severity: "HIGH",
    description: "ทัวร์ไกด์เถื่อนหลอกนักท่องเที่ยว ๒๐๐ คน เสียหายรวม ๔ ลบ.",
    lat: 7.8804, lng: 98.3923,
    address: "ภูเก็ตเมือง", province: "ภูเก็ต", district: "เมือง",
    hoursAgo: 120, reportLagMin: 1440, source: "ประชาชนแจ้ง",
    unitId: "u-prov-8-ภก", status: "INVESTIGATING",
  },
  {
    type: "ทำร้ายร่างกาย",
    severity: "MEDIUM",
    description: "ทะเลาะวิวาทย่านสถานบันเทิงป่าตอง ทำร้ายนักท่องเที่ยว",
    lat: 7.8945, lng: 98.2937,
    address: "ซอย บางลา ป่าตอง", province: "ภูเก็ต", district: "กะทู้",
    hoursAgo: 96, reportLagMin: 3, source: "191",
    unitId: "u-prov-8-ภก", status: "CLOSED", arrests: 2,
  },
  {
    type: "อุบัติเหตุ",
    severity: "HIGH",
    description: "เรือสปีดโบ๊ทชนกัน ใกล้เกาะพีพี บาดเจ็บ ๕ ราย",
    lat: 7.7300, lng: 98.7700,
    address: "ทะเลกระบี่ใกล้พีพี", province: "กระบี่", district: "เกาะพีพี",
    hoursAgo: 312, reportLagMin: 15, source: "191",
    unitId: "u-bch-8", status: "CLOSED",
  },
  {
    type: "ยาเสพติด",
    severity: "MEDIUM",
    description: "จับนักท่องเที่ยวต่างชาติ ครอบครองยาเสพติด ๒ ราย",
    lat: 7.8460, lng: 98.3387,
    address: "หาดกะรน", province: "ภูเก็ต", district: "เมือง",
    hoursAgo: 408, reportLagMin: 0, source: "ตำรวจตรวจพบ",
    unitId: "u-prov-8-ภก", status: "CLOSED", arrests: 2,
  },
  {
    type: "ลักทรัพย์",
    severity: "LOW",
    description: "ลักทรัพย์ในรีสอร์ทย่านกะตะ",
    lat: 7.8128, lng: 98.2966,
    address: "หาดกะตะ", province: "ภูเก็ต", district: "เมือง",
    hoursAgo: 552, reportLagMin: 240, source: "ประชาชนแจ้ง",
    unitId: "u-prov-8-ภก", status: "OPEN",
  },

  // ── Pattaya / ภ.๒ (6 incidents) ─────────────────────────────────
  {
    type: "ก่อความวุ่นวาย",
    severity: "MEDIUM",
    description: "ทะเลาะวิวาทกันบนถนนวอล์กกิ้งสตรีท ผู้บาดเจ็บ ๓ ราย",
    lat: 12.9322, lng: 100.8782,
    address: "วอล์กกิ้งสตรีท พัทยา", province: "ชลบุรี", district: "บางละมุง",
    hoursAgo: 72, reportLagMin: 4, source: "191",
    unitId: "u-prov-2-ชบ", status: "CLOSED", arrests: 3,
  },
  {
    type: "ยาเสพติด",
    severity: "HIGH",
    description: "บุกจับผู้ค้ายาเสพติด พัทยาใต้ ของกลางยาบ้า ๑,๒๐๐ เม็ด",
    lat: 12.9162, lng: 100.8770,
    address: "พัทยาใต้", province: "ชลบุรี", district: "บางละมุง",
    hoursAgo: 240, reportLagMin: 0, source: "ข่าวกรอง",
    unitId: "u-prov-2-ชบ", status: "CLOSED", arrests: 4,
  },
  {
    type: "ฉ้อโกง",
    severity: "MEDIUM",
    description: "นายหน้าเช่ารถยนต์เถื่อนหลอกนักท่องเที่ยวต่างชาติ",
    lat: 12.9236, lng: 100.8825,
    address: "พัทยากลาง", province: "ชลบุรี", district: "บางละมุง",
    hoursAgo: 192, reportLagMin: 720, source: "ประชาชนแจ้ง",
    unitId: "u-prov-2-ชบ", status: "INVESTIGATING",
  },
  {
    type: "อาชญากรรมออนไลน์",
    severity: "CRITICAL",
    description: "ทลายแก๊งคอลเซ็นเตอร์ ผู้ต้องหา ๑๒ ราย ของกลางคอมพ์ ๔๒ เครื่อง",
    lat: 12.9320, lng: 100.9050,
    address: "ตึกแถวพัทยาเหนือ", province: "ชลบุรี", district: "บางละมุง",
    hoursAgo: 336, reportLagMin: 0, source: "ข่าวกรอง",
    unitId: "u-bch-special-2", status: "CLOSED", arrests: 12,
  },
  {
    type: "ลักทรัพย์",
    severity: "LOW",
    description: "ลักทรัพย์ในห้องพักโรงแรม พัทยาเหนือ",
    lat: 12.9474, lng: 100.8842,
    address: "พัทยาเหนือ", province: "ชลบุรี", district: "บางละมุง",
    hoursAgo: 408, reportLagMin: 180, source: "ประชาชนแจ้ง",
    unitId: "u-prov-2-ชบ", status: "OPEN",
  },
  {
    type: "อุบัติเหตุ",
    severity: "MEDIUM",
    description: "รถจักรยานยนต์ชนต้นไม้ บริเวณถนนสุขุมวิทศรีราชา",
    lat: 13.1734, lng: 100.9272,
    address: "ถ.สุขุมวิท ศรีราชา", province: "ชลบุรี", district: "ศรีราชา",
    hoursAgo: 144, reportLagMin: 5, source: "191",
    unitId: "u-prov-2-ชบ", status: "CLOSED",
  },

  // ── Khon Kaen / ภ.๔ (5 incidents) ───────────────────────────────
  {
    type: "ยาเสพติด",
    severity: "CRITICAL",
    description: "บุกจับโกดังยาบ้า ของกลาง ๒.๑ ล้านเม็ด ผู้ต้องหา ๑๐ ราย",
    lat: 16.4419, lng: 102.8360,
    address: "นอกเมืองขอนแก่น", province: "ขอนแก่น", district: "เมือง",
    hoursAgo: 96, reportLagMin: 0, source: "ข่าวกรอง",
    unitId: "u-prov-4-ขก", status: "CLOSED", arrests: 10,
  },
  {
    type: "ยาเสพติด",
    severity: "HIGH",
    description: "สกัดรถบรรทุกยาบ้าจากชายแดน ของกลาง ๓ แสนเม็ด",
    lat: 17.8782, lng: 102.7424,
    address: "ด่านหนองคาย", province: "หนองคาย", district: "เมือง",
    hoursAgo: 168, reportLagMin: 0, source: "ข่าวกรอง",
    unitId: "u-bch-4", status: "CLOSED", arrests: 3,
  },
  {
    type: "อุบัติเหตุ",
    severity: "HIGH",
    description: "รถยนต์ชนกับรถบรรทุก ทล. ๒ อุดรธานี เสียชีวิต ๒ ราย",
    lat: 17.4138, lng: 102.7872,
    address: "ทล. ๒ อุดรธานี", province: "อุดรธานี", district: "เมือง",
    hoursAgo: 288, reportLagMin: 5, source: "191",
    unitId: "u-bch-4", status: "CLOSED",
  },
  {
    type: "ฉ้อโกง",
    severity: "MEDIUM",
    description: "แก๊งหลอกเช่าซื้อรถยนต์ ผู้เสียหาย ๒๓ ราย",
    lat: 16.4419, lng: 102.8360,
    address: "ใจกลางขอนแก่น", province: "ขอนแก่น", district: "เมือง",
    hoursAgo: 528, reportLagMin: 2880, source: "ประชาชนแจ้ง",
    unitId: "u-prov-4-ขก", status: "INVESTIGATING",
  },
  {
    type: "ทำร้ายร่างกาย",
    severity: "LOW",
    description: "ความขัดแย้งในบ้านพัก ผู้บาดเจ็บเล็กน้อย ๑ ราย",
    lat: 16.4380, lng: 102.8430,
    address: "ชุมชนเมืองขอนแก่น", province: "ขอนแก่น", district: "เมือง",
    hoursAgo: 360, reportLagMin: 120, source: "ประชาชนแจ้ง",
    unitId: "u-prov-4-ขก", status: "CLOSED",
  },

  // ── 3 จว.ใต้ / ภ.๙ (5 incidents) ────────────────────────────────
  {
    type: "ก่อความวุ่นวาย",
    severity: "CRITICAL",
    description: "ลอบวางระเบิดด้านนอกสภ. ผู้บาดเจ็บ ๒ ราย",
    lat: 6.8755, lng: 101.2502,
    address: "ใจกลางเมืองยะลา", province: "ยะลา", district: "เมือง",
    hoursAgo: 72, reportLagMin: 1, source: "191",
    unitId: "u-bch-9", status: "INVESTIGATING",
  },
  {
    type: "อื่นๆ",
    severity: "HIGH",
    description: "พบวัตถุต้องสงสัย เก็บกู้ระเบิดสำเร็จ",
    lat: 6.4254, lng: 101.8203,
    address: "อ.เบตง", province: "ยะลา", district: "เบตง",
    hoursAgo: 144, reportLagMin: 0, source: "ข่าวกรอง",
    unitId: "u-bch-9", status: "CLOSED",
  },
  {
    type: "ทำร้ายร่างกาย",
    severity: "CRITICAL",
    description: "ลอบทำร้ายข้าราชการ ปัตตานี เสียชีวิต ๑ ราย",
    lat: 6.8692, lng: 101.2503,
    address: "ปัตตานี เมือง", province: "ปัตตานี", district: "เมือง",
    hoursAgo: 216, reportLagMin: 5, source: "191",
    unitId: "u-bch-9", status: "INVESTIGATING",
  },
  {
    type: "ยาเสพติด",
    severity: "MEDIUM",
    description: "จับกุมผู้ค้ายาบ้ารายย่อยในชุมชน",
    lat: 6.4254, lng: 101.8203,
    address: "อ.เบตง", province: "ยะลา", district: "เบตง",
    hoursAgo: 312, reportLagMin: 0, source: "ตำรวจตรวจพบ",
    unitId: "u-bch-9", status: "CLOSED", arrests: 1,
  },
  {
    type: "อุบัติเหตุ",
    severity: "MEDIUM",
    description: "รถจักรยานยนต์ชนกัน ทล. ๔๓ สงขลา-นราธิวาส",
    lat: 6.0252, lng: 101.7117,
    address: "ทล. ๔๓ ใกล้ปลายแหลม", province: "นราธิวาส", district: "เมือง",
    hoursAgo: 168, reportLagMin: 5, source: "191",
    unitId: "u-bch-9", status: "CLOSED",
  },

  // ── ภ.๓ อีสานล่าง / ภ.๑ ภาคกลาง / ภ.๖ ภาคเหนือล่าง / ภ.๗ ภาคตะวันตก (mix 18 more) ──
  {
    type: "ลักทรัพย์",
    severity: "MEDIUM",
    description: "ลักทรัพย์ในห้างสรรพสินค้านครราชสีมา",
    lat: 14.9799, lng: 102.0978,
    address: "ห้างใจกลางโคราช", province: "นครราชสีมา", district: "เมือง",
    hoursAgo: 96, reportLagMin: 60, source: "ประชาชนแจ้ง",
    unitId: "u-prov-3-นม", status: "INVESTIGATING",
  },
  {
    type: "ยาเสพติด",
    severity: "HIGH",
    description: "สกัดยาบ้าจาก สปป.ลาว เข้าทางมุกดาหาร ของกลาง ๕ แสนเม็ด",
    lat: 16.5436, lng: 104.7242,
    address: "ด่านมุกดาหาร", province: "อุบลราชธานี", district: "เมือง",
    hoursAgo: 240, reportLagMin: 0, source: "ข่าวกรอง",
    unitId: "u-bch-3", status: "CLOSED", arrests: 4,
  },
  {
    type: "อุบัติเหตุ",
    severity: "CRITICAL",
    description: "รถบัสนักเรียนชน เสียชีวิต ๑ ราย บาดเจ็บ ๑๒ ราย",
    lat: 14.4870, lng: 102.8523,
    address: "ทล. ๒๔ ปากช่อง", province: "นครราชสีมา", district: "ปากช่อง",
    hoursAgo: 360, reportLagMin: 3, source: "191",
    unitId: "u-prov-3-นม", status: "CLOSED",
  },
  {
    type: "ฉ้อโกง",
    severity: "MEDIUM",
    description: "เสริมสวยเถื่อนหลอกผู้เสียหายฉีดสารเสริมจมูก",
    lat: 14.4751, lng: 101.3777,
    address: "อ.กบินทร์บุรี", province: "ปราจีนบุรี", district: "กบินทร์บุรี",
    hoursAgo: 408, reportLagMin: 1440, source: "ประชาชนแจ้ง",
    unitId: "u-prov-2-ปจ", status: "INVESTIGATING",
  },
  {
    type: "อาชญากรรมออนไลน์",
    severity: "HIGH",
    description: "เว็บไซต์การพนันออนไลน์ จับกุมผู้ดูแลระบบ ๓ ราย",
    lat: 14.6730, lng: 100.5910,
    address: "อ.บางปะอิน", province: "พระนครศรีอยุธยา", district: "บางปะอิน",
    hoursAgo: 480, reportLagMin: 0, source: "ตำรวจตรวจพบ",
    unitId: "u-bch-special-2", status: "CLOSED", arrests: 3,
  },
  {
    type: "ทำร้ายร่างกาย",
    severity: "MEDIUM",
    description: "พิพาทเรื่องที่ดิน ทำร้ายร่างกาย บาดเจ็บ ๒ ราย",
    lat: 14.0228, lng: 100.7263,
    address: "อ.ธัญบุรี", province: "ปทุมธานี", district: "ธัญบุรี",
    hoursAgo: 552, reportLagMin: 30, source: "191",
    unitId: "u-prov-1-ปท", status: "CLOSED", arrests: 2,
  },
  {
    type: "ลักทรัพย์",
    severity: "LOW",
    description: "ขโมยจักรยานในมหาวิทยาลัย พิษณุโลก",
    lat: 16.8326, lng: 100.2660,
    address: "ม.นเรศวร", province: "พิษณุโลก", district: "เมือง",
    hoursAgo: 624, reportLagMin: 720, source: "ประชาชนแจ้ง",
    unitId: "u-prov-6-พล", status: "OPEN",
  },
  {
    type: "อุบัติเหตุ",
    severity: "MEDIUM",
    description: "รถยนต์พลิกคว่ำ ทล. ๑๒ ตาก",
    lat: 16.8839, lng: 99.1258,
    address: "ทล. ๑๒ ตาก-แม่สอด", province: "พิษณุโลก", district: "เมือง",
    hoursAgo: 312, reportLagMin: 8, source: "191",
    unitId: "u-bch-6", status: "CLOSED",
  },
  {
    type: "ก่อความวุ่นวาย",
    severity: "LOW",
    description: "ทะเลาะวิวาทในงานวัด",
    lat: 13.8200, lng: 100.0640,
    address: "อ.บางใหญ่", province: "นนทบุรี", district: "บางใหญ่",
    hoursAgo: 696, reportLagMin: 10, source: "191",
    unitId: "u-prov-1-นบ", status: "CLOSED",
  },
  {
    type: "ยาเสพติด",
    severity: "MEDIUM",
    description: "จับกุมผู้จำหน่ายยาบ้าในชุมชน อ.บางคล้า",
    lat: 13.7166, lng: 101.2138,
    address: "อ.บางคล้า", province: "ฉะเชิงเทรา", district: "บางคล้า",
    hoursAgo: 432, reportLagMin: 0, source: "ตำรวจตรวจพบ",
    unitId: "u-prov-2-ฉช", status: "CLOSED", arrests: 1,
  },
  {
    type: "ฉ้อโกง",
    severity: "MEDIUM",
    description: "หลอกขายแพ็คเกจทัวร์ออนไลน์ ผู้เสียหาย ๑๕ ราย",
    lat: 13.8199, lng: 100.0640,
    address: "อ.เมืองนนทบุรี", province: "นนทบุรี", district: "เมือง",
    hoursAgo: 168, reportLagMin: 2880, source: "ประชาชนแจ้ง",
    unitId: "u-prov-1-นบ", status: "INVESTIGATING",
  },
  {
    type: "อาชญากรรมออนไลน์",
    severity: "HIGH",
    description: "แก๊งหลอกลงทุนหุ้น Crypto ความเสียหาย ๓๒ ลบ.",
    lat: 13.7530, lng: 100.5340,
    address: "ใจกลางบางกอก", province: "กรุงเทพมหานคร", district: "ปทุมวัน",
    hoursAgo: 264, reportLagMin: 4320, source: "ประชาชนแจ้ง",
    unitId: "u-bch-special-2", status: "INVESTIGATING",
  },
  {
    type: "อื่นๆ",
    severity: "LOW",
    description: "พบศพชายไม่ทราบชื่อในป่า",
    lat: 14.7244, lng: 99.5310,
    address: "อ.บ้านโป่ง", province: "ราชบุรี", district: "บ้านโป่ง",
    hoursAgo: 96, reportLagMin: 240, source: "ประชาชนแจ้ง",
    unitId: "u-prov-7-รบ", status: "INVESTIGATING",
  },
  {
    type: "อุบัติเหตุ",
    severity: "MEDIUM",
    description: "เกิดอัคคีภัยในโรงงาน ไม่มีผู้บาดเจ็บ ความเสียหายราว ๕ ลบ.",
    lat: 13.6166, lng: 99.9038,
    address: "นิคมอุตสาหกรรม", province: "นครปฐม", district: "เมือง",
    hoursAgo: 360, reportLagMin: 5, source: "191",
    unitId: "u-prov-7-นฐ", status: "INVESTIGATING",
  },
  {
    type: "ลักทรัพย์",
    severity: "MEDIUM",
    description: "ขโมยร้านทอง บ้านโป่ง ของกลางทองหนัก ๒ บาท",
    lat: 13.8163, lng: 99.8731,
    address: "อ.บ้านโป่ง", province: "ราชบุรี", district: "บ้านโป่ง",
    hoursAgo: 720, reportLagMin: 30, source: "ประชาชนแจ้ง",
    unitId: "u-prov-7-รบ", status: "INVESTIGATING",
  },
  {
    type: "ทำร้ายร่างกาย",
    severity: "HIGH",
    description: "พิพาททางธุรกิจ ใช้อาวุธปืน ผู้บาดเจ็บสาหัส ๑ ราย",
    lat: 13.6260, lng: 100.0590,
    address: "อ.สามพราน", province: "นครปฐม", district: "สามพราน",
    hoursAgo: 432, reportLagMin: 4, source: "191",
    unitId: "u-prov-7-นฐ", status: "INVESTIGATING", arrests: 1,
  },
  {
    type: "ยาเสพติด",
    severity: "HIGH",
    description: "บุกจับเครือข่ายยาเสพติดในชุมชน เครือข่ายหญิงเป็นหัวหน้า",
    lat: 13.0827, lng: 99.9320,
    address: "อ.ชะอำ", province: "เพชรบุรี", district: "ชะอำ",
    hoursAgo: 504, reportLagMin: 0, source: "ข่าวกรอง",
    unitId: "u-prov-7-พบ", status: "CLOSED", arrests: 6,
  },
];

export const SEED_INCIDENTS: Incident[] = SPECS.map((spec, i) => {
  const occurredAt = hoursAgo(spec.hoursAgo);
  const reported = new Date(occurredAt);
  reported.setMinutes(reported.getMinutes() + spec.reportLagMin);
  return {
    id: rid("a", i + 1),
    type: spec.type,
    severity: spec.severity,
    description: spec.description,
    location: {
      lat: spec.lat,
      lng: spec.lng,
      address: spec.address,
      province: spec.province,
      district: spec.district,
    },
    occurredAt,
    reportedAt: reported.toISOString(),
    source: spec.source,
    unitId: spec.unitId,
    status: spec.status,
    arrests: spec.arrests,
  };
});
